### ISSUE TITLE
Navigator / icons don't always fade out on mouse inactivity

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#27]

**Comment by robbert** [comment]
They do now, and they also stay properly visible until you have switched layers.

Except in one situation: when you click on the outer circles, and then move the layers using the keyboard, the controls are shifted from under the mouse pointer. Chrome doesn't recalculate what stuff in the page the mouse is hovering then. The same thing happens when you hover over a link in this very page: the pointer will become "hand". Now scroll the page using the keyboard. The mouse pointer still is a hand, even though the hyperlink is somewhere else now. Kind of the same thing.

There no way to fix this.
