### ISSUE TITLE
Switching to HD doesn't work in FireFox

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#28]
screen goes to black, audio continues

**Comment by robbert** [comment]
The master video doesn't play in Firefox at all, so the encoding settings need to be changed for this to work:

https://s3-eu-west-1.amazonaws.com/betaofsand/MASTER+1280x1950_GRADED_25mei_15Mbps.mp4

![screen shot 2015-05-28 at 10 39 42](https://cloud.githubusercontent.com/assets/30694/7855975/e046a5b8-0525-11e5-9d4a-ba203fcc10ea.png)

**Comment by MichelvanderAa** [comment]
did you re-convert the file? Why does it have a mp4 wrapper instead of QT .mov wrapper?

**Comment by robbert** [comment]
QuickTime wrappers are generally not supported by browsers, although it might work on some OS X browsers.

I renamed the file because some browsers only look at the file extension to see if the video type is supported (they don't download a couple of bytes for [MIME sniffing](https://en.wikipedia.org/wiki/Content_sniffing)) and therefore the extension should preferably be `.mp4`.

So the file is still the same.

**Comment by robbert** [comment]
Michel, the automatic content-type recognition for the Amazon S3 doesn't work as expected after all. Next time we upload a video we should set the `Content-Type` manually again.

Bad:
![screen shot 2015-05-28 at 20 03 12](https://cloud.githubusercontent.com/assets/30694/7867205/e57f1908-0574-11e5-952d-8e20951498cc.png)

Good:

![screen shot 2015-05-28 at 20 05 41](https://cloud.githubusercontent.com/assets/30694/7867209/f08d2b46-0574-11e5-852c-8d2b3a814122.png)

**Comment by MichelvanderAa** [comment]
ok check √
