### ISSUE TITLE
Safari: audio looses sync after switching to HD

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#29]

**Comment by robbert** [comment]
It might very well be that we cannot the offer HD resolution in Safari, because in Safari the more processing power goes into video decoding the less accurate audio seeking becomes. Off course, this trade-off was known since the start of the project (although it wasn't clear all other browsers could in fact handle such high resolutions), and we always needed to find a 'sweet spot' for stream quality vs. performance.

Maybe `hd1080` still works though, we should test this.

**Comment by MichelvanderAa** [comment]
I believe this is fixed now. At least I haven't experienced it anymore
