### ISSUE TITLE
Move domain from HF website to our own

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#41]

**Comment by MichelvanderAa** [comment]
Robbert: prepare temp index page and tell Michel URL
Michel: email 123xs with URL 
:-)

**Comment by robbert** [comment]
The DNS should point to our WebFaction server:
IPv4: `81.95.157.168`.
IPv6: `2a03:8180:1001:b2:56::1b`

I have prepared the placeholder website, you can test it at:
http://bookofsand.webfactional.com/

**Comment by MichelvanderAa** [comment]
Ok I'll email 123xs now to move it

**Comment by MichelvanderAa** [comment]
email send √

**Comment by MichelvanderAa** [comment]
DNS change is done (they say, please check...)

**Comment by robbert** [comment]
Looks good to me.

![screen shot 2015-05-29 at 10 31 30](https://cloud.githubusercontent.com/assets/30694/7879135/e9835810-05ed-11e5-97d4-7575eb168893.png)

Sometimes [thebookofsand.net](http://thebookofsand.net/) doesn't appear to be working, but currently that's because the Holland Festival website is so slow.

**Comment by MichelvanderAa** [comment]
no idea what this means ;-)
